version: '3.4'
services:
  bento-backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/backend
      args:
        BACKEND_SOURCE_FOLDER: ${BACKEND_SOURCE_FOLDER}
        NEO4J_USER: ${NEO4J_USER}
        NEO4J_PASS: ${NEO4J_PASS}
    environment:
      - NEO4J_GRAPHQL_ENDPOINT=http://neo4j:7474/graphql/
      - GRAPHQL_SCHEMA=graphql/bento-extended.graphql
    depends_on:
      - neo4j
      - bento-frontend
    networks:
      - bridge
    ports:
      - 8080:8080
    restart: always

  bento-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/frontend
      args:
        FRONTEND_SOURCE_FOLDER: ${FRONTEND_SOURCE_FOLDER}
    environment:
      - REACT_APP_BACKEND_API=http://localhost:8080/v1/graphql/
      - REACT_APP_ABOUT_CONTENT_URL=https://raw.githubusercontent.com/CBIIT/bento-frontend/master/src/content/dev/aboutPagesContent.yaml
      - REACT_APP_BE_VERSION=${BACKEND_BRANCH}
      - REACT_APP_FE_VERSION=${FRONTEND_BRANCH}
    volumes:
      - ./${FRONTEND_SOURCE_FOLDER}:/usr/local/bento-frontend
      - /usr/local/bento-frontend/node_modules
    networks:
      - bridge
    ports:
      - 80:80
      - 8085:3000
    restart: always

  neo4j:
    container_name: neo4j
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/neo4j
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      - NEO4J_PASS=${NEO4J_PASS}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - bridge
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:
  neo4j-logs:

networks:
  bridge:
    driver: bridge